#DELETE FROM STD_AProduct WHERE productCode = '13' AND sys_tenantcode = 'STD_F';
#INSERT INTO STD_AProduct (programname,createdate,createtime,sys_tenantcode,createdby,updatecount,cid,unitprice,deleteflag,productcode,updatetime,productname,updatedby,updatedate) VALUES ('SimpleSql','20140619','171205','STD_F','rkinjo','0','Product','5000.00','0','13','','フリート・ファイル・コレクション　人狼（ベイオ・ウルフ）','','');
#DELETE FROM STD_AProduct WHERE productCode = '21' AND sys_tenantcode = 'STD_F';
#INSERT INTO STD_AProduct (programname,createdate,createtime,sys_tenantcode,createdby,updatecount,cid,unitprice,deleteflag,productcode,updatetime,productname,updatedby,updatedate) VALUES ('SimpleSql','20140619','171205','STD_F','rkinjo','0','Product','5000.00','0','21','','三輪車　森のとーるさん','','');
#DELETE FROM STD_AProduct WHERE productCode = '22' AND sys_tenantcode = 'STD_F';
#INSERT INTO STD_AProduct (programname,createdate,createtime,sys_tenantcode,createdby,updatecount,cid,unitprice,deleteflag,productcode,updatetime,productname,updatedby,updatedate) VALUES ('SimpleSql','20140619','171205','STD_F','rkinjo','0','Product','5000.00','0','22','','三輪車　森のうさこさん','','');
#DELETE FROM STD_AProduct WHERE productCode = '23' AND sys_tenantcode = 'STD_F';
#INSERT INTO STD_AProduct (programname,createdate,createtime,sys_tenantcode,createdby,updatecount,cid,unitprice,deleteflag,productcode,updatetime,productname,updatedby,updatedate) VALUES ('SimpleSql','20140619','171205','STD_F','rkinjo','0','Product','5000.00','0','23','','三輪車　森のぺーたさん','','');
#DELETE FROM STD_AProduct WHERE productCode = '31' AND sys_tenantcode = 'STD_F';
#INSERT INTO STD_AProduct (programname,createdate,createtime,sys_tenantcode,createdby,updatecount,cid,unitprice,deleteflag,productcode,updatetime,productname,updatedby,updatedate) VALUES ('SimpleSql','20140619','171205','STD_F','rkinjo','0','Product','5000.00','0','31','','変身ベルト DX戦極ドライバー','','');
#DELETE FROM STD_AProduct WHERE productCode = '1' AND sys_tenantcode = 'STD_A';
#INSERT INTO STD_AProduct (programname,createdate,createtime,sys_tenantcode,createdby,updatecount,cid,unitprice,deleteflag,productcode,updatetime,productname,updatedby,updatedate) VALUES ('SimpleSql','20140602','093854','STD_A','jhirai','0','Product','5000.00','0','1','','そして父になる Blu-rayスペシャル・エディション','','');
#DELETE FROM STD_AProduct WHERE productCode = '2' AND sys_tenantcode = 'STD_A';
#INSERT INTO STD_AProduct (programname,createdate,createtime,sys_tenantcode,createdby,updatecount,cid,unitprice,deleteflag,productcode,updatetime,productname,updatedby,updatedate) VALUES ('SimpleSql','20140602','093854','STD_A','jhirai','0','Product','1700.00','0','2','','七人の侍　期間限定プライス版DVD','','');
#DELETE FROM STD_AProduct WHERE productCode = '3' AND sys_tenantcode = 'STD_A';
#INSERT INTO STD_AProduct (programname,createdate,createtime,sys_tenantcode,createdby,updatecount,cid,unitprice,deleteflag,productcode,updatetime,productname,updatedby,updatedate) VALUES ('SimpleSql','20140602','093854','STD_A','jhirai','0','Product','1400.00','0','3','','ディスカバリー/ダフト・パンク CD','','');
#DELETE FROM STD_AProduct WHERE productCode = '11' AND sys_tenantcode = 'STD_A';
#INSERT INTO STD_AProduct (programname,createdate,createtime,sys_tenantcode,createdby,updatecount,cid,unitprice,deleteflag,productcode,updatetime,productname,updatedby,updatedate) VALUES ('SimpleSql','20140602','093854','STD_A','jhirai','0','Product','5000.00','0','11','','ギンガエイユウデンセツ　第15巻','','');
#DELETE FROM STD_AProduct WHERE productCode = '12' AND sys_tenantcode = 'STD_A';
#INSERT INTO STD_AProduct (programname,createdate,createtime,sys_tenantcode,createdby,updatecount,cid,unitprice,deleteflag,productcode,updatetime,productname,updatedby,updatedate) VALUES ('SimpleSql','20140602','093854','STD_A','jhirai','0','Product','5000.00','0','12','','スーパーアクションフィギュア　疾風ウォルフ（ウォルフ・デア・シュトルム）','','');
#DELETE FROM STD_AProduct WHERE productCode = '13' AND sys_tenantcode = 'STD_A';
#INSERT INTO STD_AProduct (programname,createdate,createtime,sys_tenantcode,createdby,updatecount,cid,unitprice,deleteflag,productcode,updatetime,productname,updatedby,updatedate) VALUES ('SimpleSql','20140602','093854','STD_A','jhirai','0','Product','5000.00','0','13','','フリート・ファイル・コレクション　人狼（ベイオ・ウルフ）','','');
#DELETE FROM STD_AProduct WHERE productCode = '21' AND sys_tenantcode = 'STD_A';
#INSERT INTO STD_AProduct (programname,createdate,createtime,sys_tenantcode,createdby,updatecount,cid,unitprice,deleteflag,productcode,updatetime,productname,updatedby,updatedate) VALUES ('SimpleSql','20140602','093854','STD_A','jhirai','0','Product','5000.00','0','21','','三輪車　森のとーるさん','','');
#DELETE FROM STD_AProduct WHERE productCode = '22' AND sys_tenantcode = 'STD_A';
#INSERT INTO STD_AProduct (programname,createdate,createtime,sys_tenantcode,createdby,updatecount,cid,unitprice,deleteflag,productcode,updatetime,productname,updatedby,updatedate) VALUES ('SimpleSql','20140602','093854','STD_A','jhirai','0','Product','5000.00','0','22','','三輪車　森のうさこさん','','');
#DELETE FROM STD_AProduct WHERE productCode = '23' AND sys_tenantcode = 'STD_A';
#INSERT INTO STD_AProduct (programname,createdate,createtime,sys_tenantcode,createdby,updatecount,cid,unitprice,deleteflag,productcode,updatetime,productname,updatedby,updatedate) VALUES ('SimpleSql','20140602','093854','STD_A','jhirai','0','Product','5000.00','0','23','','三輪車　森のぺーたさん','','');
#DELETE FROM STD_AProduct WHERE productCode = '31' AND sys_tenantcode = 'STD_A';
#INSERT INTO STD_AProduct (programname,createdate,createtime,sys_tenantcode,createdby,updatecount,cid,unitprice,deleteflag,productcode,updatetime,productname,updatedby,updatedate) VALUES ('SimpleSql','20140602','093854','STD_A','jhirai','0','Product','5000.00','0','31','','変身ベルト DX戦極ドライバー','','');
#DELETE FROM STD_AProduct WHERE productCode = '32' AND sys_tenantcode = 'STD_A';
#INSERT INTO STD_AProduct (programname,createdate,createtime,sys_tenantcode,createdby,updatecount,cid,unitprice,deleteflag,productcode,updatetime,productname,updatedby,updatedate) VALUES ('SimpleSql','20140602','093854','STD_A','jhirai','0','Product','5000.00','0','32','','ソニックアロー＆レモンエナジーロックシード','','');
#DELETE FROM STD_AProduct WHERE productCode = '1' AND sys_tenantcode = 'STANDARDv2';
#INSERT INTO STD_AProduct (programname,createdate,createtime,sys_tenantcode,createdby,updatecount,cid,unitprice,deleteflag,productcode,updatetime,productname,updatedby,updatedate) VALUES ('SimpleSql','20140605','124040','STANDARDv2','jhirai','0','Product','5000.00','0','1','','そして父になる Blu-rayスペシャル・エディション','','');
#DELETE FROM STD_AProduct WHERE productCode = '2' AND sys_tenantcode = 'STANDARDv2';
#INSERT INTO STD_AProduct (programname,createdate,createtime,sys_tenantcode,createdby,updatecount,cid,unitprice,deleteflag,productcode,updatetime,productname,updatedby,updatedate) VALUES ('SimpleSql','20140605','124040','STANDARDv2','jhirai','0','Product','1700.00','0','2','','七人の侍　期間限定プライス版DVD','','');
#DELETE FROM STD_AProduct WHERE productCode = '3' AND sys_tenantcode = 'STANDARDv2';
#INSERT INTO STD_AProduct (programname,createdate,createtime,sys_tenantcode,createdby,updatecount,cid,unitprice,deleteflag,productcode,updatetime,productname,updatedby,updatedate) VALUES ('SimpleSql','20140605','124040','STANDARDv2','jhirai','0','Product','1400.00','0','3','','ディスカバリー/ダフト・パンク CD','','');
#DELETE FROM STD_AProduct WHERE productCode = '11' AND sys_tenantcode = 'STANDARDv2';
#INSERT INTO STD_AProduct (programname,createdate,createtime,sys_tenantcode,createdby,updatecount,cid,unitprice,deleteflag,productcode,updatetime,productname,updatedby,updatedate) VALUES ('SimpleSql','20140605','124040','STANDARDv2','jhirai','0','Product','5000.00','0','11','','ギンガエイユウデンセツ　第15巻','','');
#DELETE FROM STD_AProduct WHERE productCode = '12' AND sys_tenantcode = 'STANDARDv2';
#INSERT INTO STD_AProduct (programname,createdate,createtime,sys_tenantcode,createdby,updatecount,cid,unitprice,deleteflag,productcode,updatetime,productname,updatedby,updatedate) VALUES ('SimpleSql','20140605','124040','STANDARDv2','jhirai','0','Product','5000.00','0','12','','スーパーアクションフィギュア　疾風ウォルフ（ウォルフ・デア・シュトルム）','','');
#DELETE FROM STD_AProduct WHERE productCode = '13' AND sys_tenantcode = 'STANDARDv2';
#INSERT INTO STD_AProduct (programname,createdate,createtime,sys_tenantcode,createdby,updatecount,cid,unitprice,deleteflag,productcode,updatetime,productname,updatedby,updatedate) VALUES ('SimpleSql','20140605','124040','STANDARDv2','jhirai','0','Product','5000.00','0','13','','フリート・ファイル・コレクション　人狼（ベイオ・ウルフ）','','');
#DELETE FROM STD_AProduct WHERE productCode = '21' AND sys_tenantcode = 'STANDARDv2';
#INSERT INTO STD_AProduct (programname,createdate,createtime,sys_tenantcode,createdby,updatecount,cid,unitprice,deleteflag,productcode,updatetime,productname,updatedby,updatedate) VALUES ('SimpleSql','20140605','124040','STANDARDv2','jhirai','0','Product','5000.00','0','21','','三輪車　森のとーるさん','','');
#DELETE FROM STD_AProduct WHERE productCode = '22' AND sys_tenantcode = 'STANDARDv2';
#INSERT INTO STD_AProduct (programname,createdate,createtime,sys_tenantcode,createdby,updatecount,cid,unitprice,deleteflag,productcode,updatetime,productname,updatedby,updatedate) VALUES ('SimpleSql','20140605','124040','STANDARDv2','jhirai','0','Product','5000.00','0','22','','三輪車　森のうさこさん','','');
#DELETE FROM STD_AProduct WHERE productCode = '23' AND sys_tenantcode = 'STANDARDv2';
#INSERT INTO STD_AProduct (programname,createdate,createtime,sys_tenantcode,createdby,updatecount,cid,unitprice,deleteflag,productcode,updatetime,productname,updatedby,updatedate) VALUES ('SimpleSql','20140605','124040','STANDARDv2','jhirai','0','Product','5000.00','0','23','','三輪車　森のぺーたさん','','');
#DELETE FROM STD_AProduct WHERE productCode = '31' AND sys_tenantcode = 'STANDARDv2';
#INSERT INTO STD_AProduct (programname,createdate,createtime,sys_tenantcode,createdby,updatecount,cid,unitprice,deleteflag,productcode,updatetime,productname,updatedby,updatedate) VALUES ('SimpleSql','20140605','124040','STANDARDv2','jhirai','0','Product','5000.00','0','31','','変身ベルト DX戦極ドライバー','','');
#DELETE FROM STD_AProduct WHERE productCode = '32' AND sys_tenantcode = 'STANDARDv2';
#INSERT INTO STD_AProduct (programname,createdate,createtime,sys_tenantcode,createdby,updatecount,cid,unitprice,deleteflag,productcode,updatetime,productname,updatedby,updatedate) VALUES ('SimpleSql','20140605','124040','STANDARDv2','jhirai','0','Product','5000.00','0','32','','ソニックアロー＆レモンエナジーロックシード','','');
#DELETE FROM STD_AProduct WHERE productCode = '1' AND sys_tenantcode = 'STD_F';
#INSERT INTO STD_AProduct (programname,createdate,createtime,sys_tenantcode,createdby,updatecount,cid,unitprice,deleteflag,productcode,updatetime,productname,updatedby,updatedate) VALUES ('SimpleSql','20140619','171205','STD_F','rkinjo','0','Product','5000.00','0','1','','そして父になる Blu-rayスペシャル・エディション','','');
#DELETE FROM STD_AProduct WHERE productCode = '2' AND sys_tenantcode = 'STD_F';
#INSERT INTO STD_AProduct (programname,createdate,createtime,sys_tenantcode,createdby,updatecount,cid,unitprice,deleteflag,productcode,updatetime,productname,updatedby,updatedate) VALUES ('SimpleSql','20140619','171205','STD_F','rkinjo','0','Product','1700.00','0','2','','七人の侍　期間限定プライス版DVD','','');
#DELETE FROM STD_AProduct WHERE productCode = '3' AND sys_tenantcode = 'STD_F';
#INSERT INTO STD_AProduct (programname,createdate,createtime,sys_tenantcode,createdby,updatecount,cid,unitprice,deleteflag,productcode,updatetime,productname,updatedby,updatedate) VALUES ('SimpleSql','20140619','171205','STD_F','rkinjo','0','Product','1400.00','0','3','','ディスカバリー/ダフト・パンク CD','','');
#DELETE FROM STD_AProduct WHERE productCode = '11' AND sys_tenantcode = 'STD_F';
#INSERT INTO STD_AProduct (programname,createdate,createtime,sys_tenantcode,createdby,updatecount,cid,unitprice,deleteflag,productcode,updatetime,productname,updatedby,updatedate) VALUES ('SimpleSql','20140619','171205','STD_F','rkinjo','0','Product','5000.00','0','11','','ギンガエイユウデンセツ　第15巻','','');
#DELETE FROM STD_AProduct WHERE productCode = '12' AND sys_tenantcode = 'STD_F';
#INSERT INTO STD_AProduct (programname,createdate,createtime,sys_tenantcode,createdby,updatecount,cid,unitprice,deleteflag,productcode,updatetime,productname,updatedby,updatedate) VALUES ('SimpleSql','20140619','171205','STD_F','rkinjo','0','Product','5000.00','0','12','','スーパーアクションフィギュア　疾風ウォルフ（ウォルフ・デア・シュトルム）','','');
#DELETE FROM STD_AProduct WHERE productCode = '32' AND sys_tenantcode = 'STD_F';
#INSERT INTO STD_AProduct (programname,createdate,createtime,sys_tenantcode,createdby,updatecount,cid,unitprice,deleteflag,productcode,updatetime,productname,updatedby,updatedate) VALUES ('SimpleSql','20140619','171205','STD_F','rkinjo','0','Product','5000.00','0','32','','ソニックアロー＆レモンエナジーロックシード','','');
#COMMIT;
